### ISSUE TITLE
Bug: gojson chokes on example JSON

### ISSUE THREAD

**Issue by faddat** [steemit/steemit-docs#2]
It's the get_block example:

{
"id": 2,
"result": {
  "previous": "003d08ff118b27e093103b580daca817342f9596",
  "timestamp": "2016-08-11T22:00:06",
  "witness": "silversteem",
  "transaction_merkle_root": "a4ed1b655c56040fd77857c2983f390fa30852cd",
  "extensions": [],
  "witness_signature": "206e7847032dd57c821fb45f880123c57a88fef17e11e4da218b7ece631d4c8338124ad02bca19710fa2376672dc2c531469f3499a208c4bf01bb990cde4ec03f0",
  "transactions": [{
    "ref_block_num": 2303,
    "ref_block_prefix": 3760687889,
    "expiration": "2016-08-11T22:00:33",
    "operations": [
      ["witness_update", {
        "owner": "supercomputing05",
        "url": "http://fxxk.com",
        "block_signing_key": "STM5b3wkzd5cPuW8tYbHpsM6qo26R5eympAQsBaoEfeMDxxUCLvsY",
        "props": {
          "account_creation_fee": "1.000 STEEM",
          "maximum_block_size": 65536,
          "sbd_interest_rate": 1000
        },
        "fee": "0.000 STEEM"
      }]
    ],
    "extensions": [],
    "signatures": []
  }

**Comment by mcifani** [comment]
Looks like there was a missing curly bracket.  Let me know if that fixes the formatting for you.

**Comment by faddat** [comment]
There was, and it did.  

However, I'm still having a lot of difficulty coming up with a schema for what get_block returns that produces a usable result for me.
